version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/.github/scripts"
    schedule:
      interval: weekly
    groups:
      pip:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: "/src/web"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: "/src/web"
    schedule:
      interval: weekly
    groups:
      docker:
        patterns: ["*"]
